name: Java CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.11
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update version
      run: mvn versions:set -DnewVersion=$VERSION --no-transfer-progress
      env:
        VERSION: ${{ github.event.release.tag_name }}
    - name: Commit
      run: |
          git config --global user.name 'gimlet2'
          git config --global user.email 'andrey.chernishov@gmail.com'
          git commit -am "Update version"
          git push origin HEAD:main

    - name: Setup GPG
      run: echo "$GPG_KEY" | gpg --import --batch --yes
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
    - name: Build with Maven
      run: ./mvnw package site:jar source:jar  --file pom.xml --no-transfer-progress
    - name: Publish to Github
      run: ./mvnw -X deploy -Pgithub  -Dgpg.keyname=$GPG_KEY_ID -Dgpg.passphrase=$GPG_KEY_PASS --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }}
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.11
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Publish to OSS
      run: ./mvnw -B package site:jar source:jar deploy -Poss-sonatype -Dgpg.keyname=$GPG_KEY_ID -Dgpg.passphrase=$GPG_KEY_PASS --no-transfer-progress
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }}
